### ISSUE TITLE
OGP Twitterカード（画像）が表示されない

### ISSUE THREAD

**Issue by AAAR-Salmon** [oucrc-org/web-2021#161]
実体があるページ：画像とページURLが相対参照になっている→絶対参照に修正
~~実体がない~~記事等のページ：~~そもそもSSRできていないので静的化しないと更新されなさそう~~デプロイ前からあったページも表示されない。よくわからん

チェックはここからできます
https://cards-dev.twitter.com/validator

**Comment by Wansuko-cmd** [comment]
記事に至ってはマジでなんも取れてないな…
記事のところとかはMicroCMSのやつを直接入れてるから大丈夫とか思ってたんやが…

**Comment by Wansuko-cmd** [comment]
TwitterとFaceBookのやつは個別に設定しないといけないとはorz

**Comment by AAAR-Salmon** [comment]
検証してみたけど<meta name="twitter:card">は書かなくてもcontent="summary"として解釈されるっぽい
やはり絶対参照にする必要がありそう

**Comment by AAAR-Salmon** [comment]
/joinは

```
INFO:  5 metatags were found
ERROR: No card found (Card error)
```

/articlesや/members以下のページは

```
WARN:  No metatags found
```

となっているところを見ると、一度404を返してしまっているのがまずいのかも(詰み)
