### ISSUE TITLE
ヘッダーに i10jan へのリンクをつけたい

### ISSUE THREAD

**Issue by smpny7** [oucrc-org/web-2021#172]
\# 新入生大歓迎

**Comment by Wansuko-cmd** [comment]
i10janのリンクなどはどこでしょうか？
書いておいた方が分かりやすいかも・・・

**Comment by smpny7** [comment]
そうやね！
> https://i10jan-api.herokuapp.com/v1.1
へのリンクをお願いします。

**Comment by smpny7** [comment]
追記です：
「入部フォーム」を削除し、「お問い合わせ」の追加をお願いします。

まとめます↓
1. ホーム
2. 作品紹介
3. 部員紹介
4. 部室の状況
5. お問い合わせ

ヘッダーのブレークポイントの変更が必要になるかもしれません。
