### ISSUE TITLE
Twitterのカードをつけたい

### ISSUE THREAD

**Issue by Wansuko-cmd** [oucrc-org/web-2021#173]
ランディングページ以外のTwitterのカードがうまいこといっていない。

他のページにランディングページの内容を丸ごとコピーしてみたが表示できなかったということで原因が分からなくなっている状態なので、直せると思った方、直していただけると助かります

**Comment by Natsu-dev** [comment]
ついでに記事の下部にTwitter共有ボタンとかあるといいかもって感じが島風

**Comment by smpny7** [comment]
@Natsu-dev Issue化しておきました💪
