### ISSUE TITLE
記事の日付形式

### ISSUE THREAD

**Issue by AAAR-Salmon** [oucrc-org/web-2021#205]
toLocaleDateStringを使ってるのにmm/dd/yyyyになってる（ということはDateオブジェクトの作り方が悪い？）
yyyy/mm/ddにしたい

**Comment by temasaguru** [comment]
![Image](https://user-images.githubusercontent.com/74000913/218234304-7def39d6-34e2-4ad0-b695-32829acb28c1.png)

Netlifyが悪さしていたらしく、`LC_ALL="ja_JP.UTF-8" npm run generate` でかいけつ

https://stackoverflow.com/a/65742733

...ややこしいので、フォーマット用ライブラリを入れよう
